name: SEED DATABASE

on:
  push:
    branches: [ develop ]

workflow_dispatch:

jobs:
  seed:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop'

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - run: npm ci
      - run: npm run seed


